### ISSUE TITLE
Component fix: Utrecht Link

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/overheidsbrede-portalen-community#118]
# Fix: Utrecht link

## Description
To use the utrecht link as a back link with an icon, the following code was added to extend it and fix icon alignment.

```css
.voorbeeld-back-link {
  align-items: center;
  column-gap: 8px;
  display: inline-flex;
}
```

If fixed in the Utrecht repo, a new class would need to be added: `utrecht-link__label` to support the following html structure

```html
<a href="" class="utrecht-link">
 <Icon />
 <span class="utrecht-link__label">Click me</span>
</a>
```
